// Code generated by "go generate". Please don't change this file directly.

package kendra

import (
	"github.com/drmmarsunited/goformation/v7/cloudformation/policies"
)

// DataSource_DataSourceConfiguration AWS CloudFormation Resource (AWS::Kendra::DataSource.DataSourceConfiguration)
// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-kendra-datasource-datasourceconfiguration.html
type DataSource_DataSourceConfiguration[T any] struct {

	// ConfluenceConfiguration AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-kendra-datasource-datasourceconfiguration.html#cfn-kendra-datasource-datasourceconfiguration-confluenceconfiguration
	ConfluenceConfiguration *DataSource_ConfluenceConfiguration[any] `json:"ConfluenceConfiguration,omitempty"`

	// DatabaseConfiguration AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-kendra-datasource-datasourceconfiguration.html#cfn-kendra-datasource-datasourceconfiguration-databaseconfiguration
	DatabaseConfiguration *DataSource_DatabaseConfiguration[any] `json:"DatabaseConfiguration,omitempty"`

	// GoogleDriveConfiguration AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-kendra-datasource-datasourceconfiguration.html#cfn-kendra-datasource-datasourceconfiguration-googledriveconfiguration
	GoogleDriveConfiguration *DataSource_GoogleDriveConfiguration[any] `json:"GoogleDriveConfiguration,omitempty"`

	// OneDriveConfiguration AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-kendra-datasource-datasourceconfiguration.html#cfn-kendra-datasource-datasourceconfiguration-onedriveconfiguration
	OneDriveConfiguration *DataSource_OneDriveConfiguration[any] `json:"OneDriveConfiguration,omitempty"`

	// S3Configuration AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-kendra-datasource-datasourceconfiguration.html#cfn-kendra-datasource-datasourceconfiguration-s3configuration
	S3Configuration *DataSource_S3DataSourceConfiguration[any] `json:"S3Configuration,omitempty"`

	// SalesforceConfiguration AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-kendra-datasource-datasourceconfiguration.html#cfn-kendra-datasource-datasourceconfiguration-salesforceconfiguration
	SalesforceConfiguration *DataSource_SalesforceConfiguration[any] `json:"SalesforceConfiguration,omitempty"`

	// ServiceNowConfiguration AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-kendra-datasource-datasourceconfiguration.html#cfn-kendra-datasource-datasourceconfiguration-servicenowconfiguration
	ServiceNowConfiguration *DataSource_ServiceNowConfiguration[any] `json:"ServiceNowConfiguration,omitempty"`

	// SharePointConfiguration AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-kendra-datasource-datasourceconfiguration.html#cfn-kendra-datasource-datasourceconfiguration-sharepointconfiguration
	SharePointConfiguration *DataSource_SharePointConfiguration[any] `json:"SharePointConfiguration,omitempty"`

	// TemplateConfiguration AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-kendra-datasource-datasourceconfiguration.html#cfn-kendra-datasource-datasourceconfiguration-templateconfiguration
	TemplateConfiguration *DataSource_TemplateConfiguration[any] `json:"TemplateConfiguration,omitempty"`

	// WebCrawlerConfiguration AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-kendra-datasource-datasourceconfiguration.html#cfn-kendra-datasource-datasourceconfiguration-webcrawlerconfiguration
	WebCrawlerConfiguration *DataSource_WebCrawlerConfiguration[any] `json:"WebCrawlerConfiguration,omitempty"`

	// WorkDocsConfiguration AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-kendra-datasource-datasourceconfiguration.html#cfn-kendra-datasource-datasourceconfiguration-workdocsconfiguration
	WorkDocsConfiguration *DataSource_WorkDocsConfiguration[any] `json:"WorkDocsConfiguration,omitempty"`

	// AWSCloudFormationDeletionPolicy represents a CloudFormation DeletionPolicy
	AWSCloudFormationDeletionPolicy policies.DeletionPolicy `json:"-"`

	// AWSCloudFormationUpdateReplacePolicy represents a CloudFormation UpdateReplacePolicy
	AWSCloudFormationUpdateReplacePolicy policies.UpdateReplacePolicy `json:"-"`

	// AWSCloudFormationDependsOn stores the logical ID of the resources to be created before this resource
	AWSCloudFormationDependsOn []string `json:"-"`

	// AWSCloudFormationMetadata stores structured data associated with this resource
	AWSCloudFormationMetadata map[string]interface{} `json:"-"`

	// AWSCloudFormationCondition stores the logical ID of the condition that must be satisfied for this resource to be created
	AWSCloudFormationCondition string `json:"-"`
}

// AWSCloudFormationType returns the AWS CloudFormation resource type
func (r *DataSource_DataSourceConfiguration[any]) AWSCloudFormationType() string {
	return "AWS::Kendra::DataSource.DataSourceConfiguration"
}
