// Code generated by "go generate". Please don't change this file directly.

package global

import (
	"github.com/drmmarsunited/goformation/v7/cloudformation/serverless"
)

// SimpleTable AWS CloudFormation Resource (SimpleTable)
// See: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlesssimpletable
type SimpleTable[T any] struct {

	// SSESpecification AWS CloudFormation Property
	// Required: false
	// See: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlesssimpletable
	SSESpecification *serverless.SimpleTable_SSESpecification[any] `json:"SSESpecification,omitempty"`
}

// AWSCloudFormationType returns the AWS CloudFormation resource type
func (r *SimpleTable[any]) AWSCloudFormationType() string {
	return "SimpleTable"
}
